[tool.commitizen]
name = "cz_conventional_commits"
version = "0.10.0"
tag_format = "v$version"
bump_message = "bump: Semantic Release Bot: Realease Version: $new_version ðŸ¤–ðŸš€ [skip ci]"
version_files = [
    ".cz.toml:version"
]
